version: '3'
services:
    backend_ocaml:
        build:
            context: ./backend/ocaml
        command: tail -f /dev/null
        depends_on:
            - "backend_database"  
        volumes:
            - ./backend/ocaml:/usr/app
        ports:
            - "3001:3001"  
    backend_database:
        build:
            context: ./backend/database
        hostname: doc
        ports:
            - "3006:3006"  
    backend_python:
        build:
            context: ./backend/python
        command: tail -f /dev/null
        volumes:
            - ./backend/python/:/usr/app
    frontend:
        build:
            context: ./frontend/
        command: tail -f /dev/null
        volumes:
            - ./frontend/:/usr/app
        ports:
            - "3000:3000"