version: '3'
services:
    backend_ocaml:
        build:
            context: ./backend/ocaml
        command: echo 'Backend Started'
        depends_on:
            - "backend_database"  
        volumes:
            - ./backend/ocaml:/usr/app
        ports:
            - "3001:3001"  
    backend_database:
        build:
            context: ./backend/database
        hostname:
            database
        ports:
            - "3006:3006"  
    frontend:
        build:
            context: ./frontend/
        command: echo 'Frontend Started'
        volumes:
            - ./frontend/:/usr/app
        ports:
            - "3000:3000"