version: '3'
services:
  backend_go:
    build:
      context: ./backend/go
    command: echo 'Backend Started'
    volumes:
      - ./backend/go:/usr/app
    ports:
      - "3002:3002"
  backend_ocaml:
    build:
        context: ./backend/ocaml
    command: echo 'Backend Started'
    volumes:
      - ./backend/ocaml:/usr/app
    ports:
      - "3001:3001"  
  frontend:
    build:
      context: ./frontend/
    command: echo 'Frontend Started'
    volumes:
      - ./frontend/:/usr/app
    ports:
      - "3000:3000"